GET https://masacr3bot.pythonanywhere.com/usuarios

###
POST https://masacr3bot.pythonanywhere.com/montos
Content-Type: application/json

{
    "id": "fa9ed989-a30a-4c13-9d46-0f2c100bf2ed",
    "monto" : [200, 300],
    "nombre" : "leo"
}

###
POST https://masacr3bot.pythonanywhere.com/pagar
Content-Type: application/json

{
    "id": "4af5b170-260c-4cc7-9118-246d9098fed6",
    "nombre": "lorena",
    "deuda_total": 14,
    "pago_del_usuario": 20,
    "monto": [3,1,10],
    "fecha": "2024-07-19T19:03:30.363Z"
}

###
GET https://masacr3bot.pythonanywhere.com/pagar